# permissions for end users to view bizteams.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bizteam-viewer-role
rules:
- apiGroups:
  - core.wutong.io
  resources:
  - bizteams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wutong.io
  resources:
  - bizteams/status
  verbs:
  - get
