# permissions for end users to view syscomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: syscomponent-viewer-role
rules:
- apiGroups:
  - core.wutong.io
  resources:
  - syscomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wutong.io
  resources:
  - syscomponents/status
  verbs:
  - get
