# permissions for end users to edit bizapplications.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bizapplication-editor-role
rules:
- apiGroups:
  - core.wutong.io
  resources:
  - bizapplications
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - core.wutong.io
  resources:
  - bizapplications/status
  verbs:
  - get
