# permissions for end users to view bizcomponents.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: bizcomponent-viewer-role
rules:
- apiGroups:
  - core.wutong.io
  resources:
  - bizcomponents
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - core.wutong.io
  resources:
  - bizcomponents/status
  verbs:
  - get
